add_test( [==[Image lighten() lightens pixels by 0.1]==] /workspaces/cs225git/mp_stickers/src/test [==[Image lighten() lightens pixels by 0.1]==]  )
set_tests_properties( [==[Image lighten() lightens pixels by 0.1]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image lighten() does not lighten a pixel above 1.0]==] /workspaces/cs225git/mp_stickers/src/test [==[Image lighten() does not lighten a pixel above 1.0]==]  )
set_tests_properties( [==[Image lighten() does not lighten a pixel above 1.0]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image darken(0.2) darkens pixels by 0.2]==] /workspaces/cs225git/mp_stickers/src/test [==[Image darken(0.2) darkens pixels by 0.2]==]  )
set_tests_properties( [==[Image darken(0.2) darkens pixels by 0.2]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image darken(0.2) does not darken a pixel below 0.0]==] /workspaces/cs225git/mp_stickers/src/test [==[Image darken(0.2) does not darken a pixel below 0.0]==]  )
set_tests_properties( [==[Image darken(0.2) does not darken a pixel below 0.0]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image saturate() saturates a pixels by 0.1]==] /workspaces/cs225git/mp_stickers/src/test [==[Image saturate() saturates a pixels by 0.1]==]  )
set_tests_properties( [==[Image saturate() saturates a pixels by 0.1]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image rotateColor(double) rotates the color]==] /workspaces/cs225git/mp_stickers/src/test [==[Image rotateColor(double) rotates the color]==]  )
set_tests_properties( [==[Image rotateColor(double) rotates the color]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image rotateColor(double) keeps the hue in the range 0..360]==] /workspaces/cs225git/mp_stickers/src/test [==[Image rotateColor(double) keeps the hue in the range 0..360]==]  )
set_tests_properties( [==[Image rotateColor(double) keeps the hue in the range 0..360]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image scale(2.0) results in the correct width/height]==] /workspaces/cs225git/mp_stickers/src/test [==[Image scale(2.0) results in the correct width/height]==]  )
set_tests_properties( [==[Image scale(2.0) results in the correct width/height]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image scale(0.5) results in the correct width/height]==] /workspaces/cs225git/mp_stickers/src/test [==[Image scale(0.5) results in the correct width/height]==]  )
set_tests_properties( [==[Image scale(0.5) results in the correct width/height]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image scale(2) scales pixel data in a reasonable way]==] /workspaces/cs225git/mp_stickers/src/test [==[Image scale(2) scales pixel data in a reasonable way]==]  )
set_tests_properties( [==[Image scale(2) scales pixel data in a reasonable way]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[Image scale(0.5) scales pixel data in a reasonable way]==] /workspaces/cs225git/mp_stickers/src/test [==[Image scale(0.5) scales pixel data in a reasonable way]==]  )
set_tests_properties( [==[Image scale(0.5) scales pixel data in a reasonable way]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[A StickerSheet with no stickers works]==] /workspaces/cs225git/mp_stickers/src/test [==[A StickerSheet with no stickers works]==]  )
set_tests_properties( [==[A StickerSheet with no stickers works]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet does not duplicate stickers in memory]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet does not duplicate stickers in memory]==]  )
set_tests_properties( [==[StickerSheet does not duplicate stickers in memory]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet behaves correctly when a sticker is updated]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet behaves correctly when a sticker is updated]==]  )
set_tests_properties( [==[StickerSheet behaves correctly when a sticker is updated]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::addSticker() adds a new layer when sheet is full]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::addSticker() adds a new layer when sheet is full]==]  )
set_tests_properties( [==[StickerSheet::addSticker() adds a new layer when sheet is full]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::setStickerAtLayer() adds to the correct layer]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::setStickerAtLayer() adds to the correct layer]==]  )
set_tests_properties( [==[StickerSheet::setStickerAtLayer() adds to the correct layer]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::setStickerAtLayer() past the top layer]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::setStickerAtLayer() past the top layer]==]  )
set_tests_properties( [==[StickerSheet::setStickerAtLayer() past the top layer]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::removeSticker() can remove the last sticker]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::removeSticker() can remove the last sticker]==]  )
set_tests_properties( [==[StickerSheet::removeSticker() can remove the last sticker]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::removeSticker() can remove the first sticker]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::removeSticker() can remove the first sticker]==]  )
set_tests_properties( [==[StickerSheet::removeSticker() can remove the first sticker]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::removeSticker() can remove all stickers]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::removeSticker() can remove all stickers]==]  )
set_tests_properties( [==[StickerSheet::removeSticker() can remove all stickers]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::getSticker() returns the sticker]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::getSticker() returns the sticker]==]  )
set_tests_properties( [==[StickerSheet::getSticker() returns the sticker]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::getSticker() returns NULL for a non-existant sticker]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::getSticker() returns NULL for a non-existant sticker]==]  )
set_tests_properties( [==[StickerSheet::getSticker() returns NULL for a non-existant sticker]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::getSticker() returns NULL for a removed sticker]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::getSticker() returns NULL for a removed sticker]==]  )
set_tests_properties( [==[StickerSheet::getSticker() returns NULL for a removed sticker]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::translate() translates a sticker's location]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::translate() translates a sticker's location]==]  )
set_tests_properties( [==[StickerSheet::translate() translates a sticker's location]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet::translate() returns false for a non-existant sticker]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet::translate() returns false for a non-existant sticker]==]  )
set_tests_properties( [==[StickerSheet::translate() returns false for a non-existant sticker]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[A complex StickerSheet is correct]==] /workspaces/cs225git/mp_stickers/src/test [==[A complex StickerSheet is correct]==]  )
set_tests_properties( [==[A complex StickerSheet is correct]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet's copy constructor makes an independent copy]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet's copy constructor makes an independent copy]==]  )
set_tests_properties( [==[StickerSheet's copy constructor makes an independent copy]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[StickerSheet's assignment operator makes an independent copy]==] /workspaces/cs225git/mp_stickers/src/test [==[StickerSheet's assignment operator makes an independent copy]==]  )
set_tests_properties( [==[StickerSheet's assignment operator makes an independent copy]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[A StickerSheet with stickers at negative coordinates works]==] /workspaces/cs225git/mp_stickers/src/test [==[A StickerSheet with stickers at negative coordinates works]==]  )
set_tests_properties( [==[A StickerSheet with stickers at negative coordinates works]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
add_test( [==[A StickerSheet with stickers placed beyond base image boundaries works]==] /workspaces/cs225git/mp_stickers/src/test [==[A StickerSheet with stickers placed beyond base image boundaries works]==]  )
set_tests_properties( [==[A StickerSheet with stickers placed beyond base image boundaries works]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225git/mp_stickers/src)
set( test_TESTS [==[Image lighten() lightens pixels by 0.1]==] [==[Image lighten() does not lighten a pixel above 1.0]==] [==[Image darken(0.2) darkens pixels by 0.2]==] [==[Image darken(0.2) does not darken a pixel below 0.0]==] [==[Image saturate() saturates a pixels by 0.1]==] [==[Image rotateColor(double) rotates the color]==] [==[Image rotateColor(double) keeps the hue in the range 0..360]==] [==[Image scale(2.0) results in the correct width/height]==] [==[Image scale(0.5) results in the correct width/height]==] [==[Image scale(2) scales pixel data in a reasonable way]==] [==[Image scale(0.5) scales pixel data in a reasonable way]==] [==[A StickerSheet with no stickers works]==] [==[StickerSheet does not duplicate stickers in memory]==] [==[StickerSheet behaves correctly when a sticker is updated]==] [==[StickerSheet::addSticker() adds a new layer when sheet is full]==] [==[StickerSheet::setStickerAtLayer() adds to the correct layer]==] [==[StickerSheet::setStickerAtLayer() past the top layer]==] [==[StickerSheet::removeSticker() can remove the last sticker]==] [==[StickerSheet::removeSticker() can remove the first sticker]==] [==[StickerSheet::removeSticker() can remove all stickers]==] [==[StickerSheet::getSticker() returns the sticker]==] [==[StickerSheet::getSticker() returns NULL for a non-existant sticker]==] [==[StickerSheet::getSticker() returns NULL for a removed sticker]==] [==[StickerSheet::translate() translates a sticker's location]==] [==[StickerSheet::translate() returns false for a non-existant sticker]==] [==[A complex StickerSheet is correct]==] [==[StickerSheet's copy constructor makes an independent copy]==] [==[StickerSheet's assignment operator makes an independent copy]==] [==[A StickerSheet with stickers at negative coordinates works]==] [==[A StickerSheet with stickers placed beyond base image boundaries works]==])
